### ISSUE TITLE
Nesprávna cesta ku komponentu v rozšírenej pätičke

### ISSUE THREAD

**Issue by frkosk** [id-sk/id-sk-frontend#105]
https://github.com/id-sk/id-sk-frontend/blob/8e38fab091df93119233d2060806713e44a834a7/src/idsk/components/footer-extended/template.njk#L1

Keď som IDSK použil ako npm balíček v projekte, tak mi pri kompilovaní šabĺony nenájde použitý govuk komponent.
Cesta by mala byť asi takto ../../../govuk/components/details/macro.njk

**Comment by frkosk** [comment]
#106 urobil som k tomu fix

**Comment by LubosKat** [comment]
Kolega nakoniec ten import vymazal cely, pretoze dostalo sa to tam nejakym nedopatrenim..
