### ISSUE TITLE
README: neplatny link na metodicke usmernenie

### ISSUE THREAD

**Issue by klimeto** [id-sk/id-sk-frontend#121]
Ahojte,

V README subore je neplatny link na metodicke usmernienie na budovanie Frontend sluzieb pomocou IDSK. 

Je to tento link: https://idsk-preview.herokuapp.com/uvod/metodika-ucd

Mozete to prosim opravit?

Dakujem

**Comment by LubosKat** [comment]
Dobry den,

dakujeme pekne za pripomienku. Opravene a nasadene: https://idsk.gov.sk/uvod/metodika-ucd
