### ISSUE TITLE
Pretekanie obrazkov na mobilnych velkostiach

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#13]
Pokial obrazok presiahne viewport, tak na mobile preteka + sa vytvori (zrejme nezelany) horizontalny scrollbar.

https://idsk-elements.herokuapp.com/vzory/stranky-dokoncenia-procesu

Tested on:
- Safari, iOS 13.4.1
- Safari 13.1, macOS
- Chrom 81.0.4044.122, macOS

![Image from iOS](https://user-images.githubusercontent.com/26273789/80574250-c997f180-8a01-11ea-93d3-7b347d567231.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/26273789/80574255-cb61b500-8a01-11ea-91ed-676d9059bd7f.png)

**Comment by frkosk** [comment]
Opravené
