### ISSUE TITLE
Absolutne linky na assets

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#162]
Pri pouzivani https://github.com/id-sk/id-sk-frontend/blob/master/dist/idsk-frontend.min.css robia problem linky na assets, konkretne su napr. nalinkovane fonty `/assets/fonts`, pricom v mojom pripade mam tieto subory na inej URL.

Fajn by bolo zmenit na relativne referencovanie.

**Comment by oliverfindl** [comment]
Zdravim,

riesim podobny problem. Potrebujem odstranit/opodmienkovat definiciu fontu Source Sans Pro, nakolko tento font nie je zahrnuty v tomto repozitari aj ked sa zdrojaky na neho referencuju. Momentalne mam cele assets nasymlinkovane z node_modules do svojej statiky, cize aj keby som si ho stiahol a umiestnil tam kde ma byt, pri dalsej aktualizacii by mi to opat zmyzlo...

Kazdopadne, nazad k vasej issue. Cesta k assets sa da nakonfigurovat podla potreby.

https://github.com/id-sk/id-sk-frontend/blob/0ff2eaa734670bce7861f37bfeb8eb92a0226ca1/src/idsk/overrides/_assets.scss#L5-L28

**Comment by ondond** [comment]
> Kazdopadne, nazad k vasej issue. Cesta k assets sa da nakonfigurovat podla potreby.

To neriesi moj problem, lebo pouzivam vybuildovane zdrojaky - v mojom pouziti nema velky zmysel si IDSK separatne buildovat (nemam ambiciu do IDSK robit zasahy).

**Comment by oliverfindl** [comment]
> > Kazdopadne, nazad k vasej issue. Cesta k assets sa da nakonfigurovat podla potreby.
> 
> To neriesi moj problem, lebo pouzivam vybuildovane zdrojaky - v mojom pouziti nema velky zmysel si IDSK separatne buildovat (nemam ambiciu do IDSK robit zasahy).

Buildovanie CSS je v dnesnej dobe uz standardom. Kazdy uzivatel si moze cez premenne ponastavovat vlastne farby, rozmery, fonty, podmienky pre dalsie komponenty a podobne (vseobecne, nie len v ramci [id-sk](https://github.com/id-sk/id-sk-frontend)). Je to doslova  otazka jedneho spustenia [node-sass](https://github.com/sass/node-sass), popr. ide to este doplnit o [stylelint](https://github.com/stylelint/stylelint), [postcss](https://github.com/postcss/postcss), [purgecss](https://github.com/FullHuman/purgecss) a podobne. Ja to mam takto nastavene snad pre kazdy projekt, kedze vsade pouzivam SCSS. Vo vysledku z toho dostanem vystup, ktory ma napr. len 10% - 20% povodnej velkosti.

Ale inak suhlasim, ze v zakladnom nastaveni absolutna cesta nedava zmysel.

**Comment by oliverfindl** [comment]
Po aktualizacii balicka som zistil, ze sa cesta k assetom (minimalne pre fonty) zmenila z premennej `$govuk-assets-path` na `$idsk-assets-path`. Ako nechcem byt zly, ale breaking changes mozu byt az v major verzii a nie v minor verzii.

**Comment by adriKosa** [comment]
IDSK nepoužíva absolútne cesty k priečinkom. Cesta /assets/fonts je relatívna. V prípade používania minifikovanej verzie máme návod ako importovať assety: https://idsk.gov.sk/uvod/instalacia-pomocou-dist  Odporúčame použiť inštaláciu cez npm a cez sass premenné nastaviť cesty k assetom podľa vaše adresárovej štruktúry. Návod: https://idsk.gov.sk/uvod/instalacia-pomocou-npm

**Comment by ondond** [comment]
@adriKosa To nie je pravda, prosim pozrite si https://github.com/id-sk/id-sk-frontend/blob/master/dist/idsk-frontend-2.9.0.min.css a dajte vyhladavat `(/assets/` - mne to dava 33 vysledkov, ci zle vidim?
