### ISSUE TITLE
Preklad "Open all" a "Close all" v accordion

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#164]
Bolo by fajn prelozit "Open all" a "Close all" pre komponent [Accordion](https://idsk.gov.sk/components/accordion).

Na https://vakcinacia.nczisk.sk/ sa s tym popasovali svojsky (svojim vlastnym overrideom).

<img width="1035" alt="ID-SK_Frontend" src="https://user-images.githubusercontent.com/26273789/111495235-72952b00-873f-11eb-9b59-15fcd48a7f4d.png">

**Comment by LubosKat** [comment]
Dobry den,

dakujeme pekne za postreh, opravene a nasadene.
