### ISSUE TITLE
Linky v release notes + slovenske nazvy

### ISSUE THREAD

**Issue by vladovarga** [id-sk/id-sk-frontend#231]
Toto je len request pre lepsiu orientanciu v novo vydanych releasoch...

Vedeli by sme prosim pouzit hyperlinky v release notes priamo na web idsk.gov.sk ku konkretnym novo pridanym komponentom/vzorom ?

Idealne ich aj pomenovat po slovensky, tak ako sa ocitnu na stranke idsk.gov.sk.

Diky

**Comment by LubosKat** [comment]
Dobry den,

dakujeme pekne za pripomienku. Zapracovali sme na nej a najnovsie release notes si mozete prezriet tu: https://github.com/id-sk/id-sk-frontend/releases/tag/2.6.1 . Zaroven este planujeme aj zverejnovat zoznam releasov s odkazmi na dany release notes na stranke idsk.gov.sk v casti uvod, co by malo vyjst v najblizsom release.
