### ISSUE TITLE
Source Sans Pro

### ISSUE THREAD

**Issue by oliverfindl** [id-sk/id-sk-frontend#285]
Pri tomto fonte som narazil na viacero problemov.

1. Nie je sucastou tohto repozitaru, i ked (S)CSS ho referencuje v ramci struktury tohto repozitaru.
2. Nenasiel som zmienku, odkial si je mozne tento font stiahnut v pozadovanom formate. Nakoniec som skoncil s tym, ze som si ho stiahol priamo z [idsk.gov.sk](https://idsk.gov.sk).
3. Neexistuje SCSS premenna, ktora by tento font dokazala vylucit z CSS. Skusal som si spravit jednoduchu webstranku (hlavicka, omrvinky, obrazok, cca. 1 obrazovka textu a paticka) a bol som celkom nemilo prekvapeny z toho, ze cela webstranka ma 195 kB a z toho je cca. 150 kB len font Source Sans Pro Regular + Bold.

**Comment by oliverfindl** [comment]
Po aktualizacii balicka a opatovnom vybuildovani CSS pomocou [node-sass](https://github.com/sass/node-sass) som zistil, ze sa v CSS nachadza definicia fontov 2x. Jedna je hned na zaciatku suboru a druha je na rovnakom mieste, ako je vo vybuildovanom CSS v tomto repozitari. Toto ma za nasledok stav, kedy browser vo vacsine pripadov requestne kazdy font 2x (ak sa mu medzicasom nevrati response z predchadzajuceho resourcu, ktory ostane nasledne v cache), co vo vysledku robi takmer 300 kB.

Priklad:

```scss
// app.scss

@charset "utf-8";

$idsk-assets-path: "/static/";

@import "./node_modules/@id-sk/frontend/idsk/all.scss";
```

```bash
$ npx node-sass app.scss app.css
```

**Comment by Kvaso1** [comment]
Opravene v release 2.8.0
https://github.com/id-sk/id-sk-frontend/releases/tag/2.8.0
