### ISSUE TITLE
Uvodny blok - zarovnanie

### ISSUE THREAD

**Issue by 5ulo** [id-sk/id-sk-frontend#317]
V dokumentacii sa pise:

_Komponent populárny obsah má tri základné variácie pozadia: **bez pozadia (so zarovnaním vpravo)**, so šedým a s modrým pozadím (so zarovnaním vľavo za pomoci odrážok)._

https://idsk.gov.sk/komponenty/intro-block

V prikladoch je vsak variant bez pozadia zarovnany vlavo. Kde je pravda?

**Comment by Kvaso1** [comment]
Opravene v release 2.8.0
https://github.com/id-sk/id-sk-frontend/releases/edit/2.8.0
