### ISSUE TITLE
Problemy v pristupnosti

### ISSUE THREAD

**Issue by 5ulo** [id-sk/id-sk-frontend#318]
Ako priklad uvediem homepage pre webove sidlo
https://idsk.gov.sk/vzory/homepage

Focus na button Vyhladavania v intro-blocku - zlty background a biela ikonka, kontrast 1.33, fail
`.idsk-blue-banner .govuk-link`- detto pri focus stave, kontrast 1.33, fail
Linky v kartickach su modre s underline, hover je cierny s underline.. tiez mi pride farebny rozdiel pri tychto stavoch maly a mali by byt nejako odlisene - bud hrubsi underline, aelbo bodkovany.. whatever

Vsetky dropdown navigacie - ci uz hlavna navigacia, alebo jazyky, (vid napr. tu https://idsk.gov.sk/komponenty/hlavicka-webove-sidla) sa nedaju zavriet klavesou ESC ak chce uzivatel zo submenu odist, musi ho cely preklikat. Otvaranie submenu ma byt na poziadanie a malo by sa aj na poziadanie vediet zavriet - vid Bootstrap dorpdown

**Comment by Kvaso1** [comment]
Opravene v release 2.8.0
https://github.com/id-sk/id-sk-frontend/releases/edit/2.8.0
