### ISSUE TITLE
webpack problem  s initAll 

### ISSUE THREAD

**Issue by hulvat** [id-sk/id-sk-frontend#324]
Dobry den
ked pouzijem pre webpack setup aky mate na stranke
```
import { initAll } from  'govuk-frontend';
initAll();
```
tak nefunguju komponenty zavisle na js, napr govuk-accordion

Konfiguracia webpack je nasledovna

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const isDevelopment = process.env.NODE_ENV === 'development';


module.exports = {
  mode: 'development',
  entry: ['./src/index.js'],
  devtool: 'inline-source-map',
  devServer: {
    static: './dist',
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Output Management',
      template: './src/template.html',
      inject: 'body',
      hash: true
    }),
    new MiniCssExtractPlugin()
  ],
  output: {
    filename: '[name]bundle.js',
    path: path.resolve(__dirname, 'dist'),
    clean: true,
  },
  module: {
    rules: [
      {
        test: /\.(s(a|c)ss)$/,
        use: [
          MiniCssExtractPlugin.loader, 
          'css-loader',"sass-loader"
         ],
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/i,
        type: 'asset/resource',
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        type: 'asset/resource',
      },
    ],
  },
};
```
konzola ale nehlasi ziadnu chybu

**Comment by hulvat** [comment]
Pripajam este vybuildovany js 
[bundle.zip](https://github.com/id-sk/id-sk-frontend/files/7532650/bundle.zip)

**Comment by 5ulo** [comment]
skus dat priamo do html body na uplny koniec
```
<script>window.GOVUKFrontend.initAll()</script>
```

**Comment by hulvat** [comment]
> skus dat priamo do html body na uplny koniec
> 
> ```
> <script>window.GOVUKFrontend.initAll()</script>
> ```
Dik.
Takymto sposobom to funguje v pohode a tak som to zatial aj obisiel, ale chcel som to vsetko mat v jednom vyexportovanom javascripte.

**Comment by 5ulo** [comment]
ja som siel tou istou cestou ako ty a pri prvom projekte som presne toto iste riesil. Nemali to vtedy v dokumentacii, nasiel som to v dokumentacii priamo gov-uk.
Priklad pre idsk je aj tu https://idsk.gov.sk/uvod/instalacia-pomocou-dist

**Comment by adriKosa** [comment]
Ďakujeme za pripomienky. Treba použiť nasledujúci import
`import { initAll } from  '@id-sk/frontend';
initAll();`
Pripomienky budú zapracované v najbližšom release.
