### ISSUE TITLE
problemy s assetmi

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#361]
V `/dist/` adresari zrejme chyba cely folder `./assets/images/header-web/`. Zaroven assety su linkovane absolutnou cestou v CSS, co sposobuje problemy pri inom umiestneni ako v root-e. Konkretne napr.:
- `/assets/images/header-web/navigation-arrow.svg`
- `/assets/images/header-web/navigation-arrow-mobile.svg`

ale aj x dalsich, treba to cele popozerat.

**Comment by ondond** [comment]
Cast problemu uz bola hlasena v #162

**Comment by adriKosa** [comment]
Assety pre header-web boli doplnené v novej verzií 2.9.0. IDSK nepoužíva absolútne cesty k priečinkom. Cesta /assets/fonts je relatívna. V prípade používania minifikovanej verzie máme návod ako importovať assety: https://idsk.gov.sk/uvod/instalacia-pomocou-dist  Odporúčame použiť inštaláciu cez npm a cez sass premenné nastaviť cesty k assetom podľa vaše adresárovej štruktúry. Návod: https://idsk.gov.sk/uvod/instalacia-pomocou-npm
