### ISSUE TITLE
Chýbajúci import tools/all.scss + image-url

### ISSUE THREAD

**Issue by Hectix** [id-sk/id-sk-frontend#362]
V priečinku `tools` sa nachadzajú dôležité funkcie na importovanie fontov a images. Vidím tam 2 problémy:

1. V `tools/all.scss` sa neimportuje `_image-url.scss` v ktorom je zadefinovaná funkcia idsk-image-url.
2. Súbor `tools/all.scss` sa nikde nepoužíva (používa sa iba `font-url.scss` v overrides/_font-faces.scss)

Práve kvôli tomu vzniknú problémy s `css-loader` - napr. `Can't resolve image '...' in '...'` pretože funkcia `idsk-image-url` neexistuje.

**Comment by adriKosa** [comment]
Ďakujeme za pripomienky. Toto už bolo uzavreté v inej issue. https://github.com/id-sk/id-sk-frontend/pull/364
