### ISSUE TITLE
TAB trap v headeri

### ISSUE THREAD

**Issue by 5ulo** [id-sk/id-sk-frontend#371]
Pri prechadzani stranky TABulatorom je problem vyjst z headeru. Aplikujete Tab trap na header na desktopovej verzi. Nechcete sa uz vykaslat na vymyslanie kolesa a postavit to uz na nejakom normalnom frameworku, ktory ma pristupnost uz vyriesenu? Bootstrap napriklad?

vid video: posledna polozka v navigacii je naozaj posledna. Mozte trieskat do TABu kolko len chcete
https://user-images.githubusercontent.com/4980919/157689430-f59a1afb-0cba-43d8-b2d8-7376d9c2a5f8.mov

**Comment by robertsopko** [comment]
Bolo fixnute vo verzii 2.10.0
