### ISSUE TITLE
sass warning

### ISSUE THREAD

**Issue by Droutin** [id-sk/id-sk-frontend#384]
Dobrý deň,

ID-SK používame v projekte pre obecný úrad Prešov. Problém je v tom, že nové sass vyhadzuje Deprecation Warning v prípade matematických operácií. Príklad:
![image](https://user-images.githubusercontent.com/17362753/165510281-6eace0e2-faca-4916-8aaf-a3c125b746f4.png)

V prípade importu celého balíčka `all.scss` trvá build nadmerne dlho kvoli kontrole.

**Comment by skodapetr** [comment]
Those can be easily fixed, yet many of the warnings are from the _govuk_  "sub-package".
Is it ok to fix them in this repository? The "How to contribute" does not provide an answer.
