### ISSUE TITLE
HeaderWeb language list has wrong position on mobile

### ISSUE THREAD

**Issue by LordZombi** [id-sk/id-sk-frontend#397]
On mobile devices, eg. Safari browser when scrolled down and header is sticky, language menu flows randomly:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/4995946/178940759-4b581613-d4f1-4d3c-a118-88ae0f8de6a5.png">

You can't have position fixed (language list) inside position sticky (header).

Again, please enable PRs so public can help improve state services.

**Comment by robertsopko** [comment]
This has been already fixed (language list position changed to absolute).
