### ISSUE TITLE
Video a obrazky "pretekaju" cez container

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#53]
Obrazky a videa ked sa includenu napr. v
`<div class="govuk-grid-row"> <div class="govuk-grid-column-full">`
tak pretekaju cez container. 

Moj fix ako genericky override, mozno dirty, neodvazil som sa s tym hrat priamo v repe:
`video, img {
  width: 100%;
}`

**Comment by LubosKat** [comment]
Dobry den,

dakujeme pekne za postreh, opravene a nasadene: https://github.com/id-sk/id-sk-frontend/releases/tag/2.6.1

**Comment by ondond** [comment]
Dobry den, kde konkretne? Lebo pri update na 2.8.0 mi to stale preteka a nenasiel som to ani v styloch v inspectore... (konkretne v2.6.1 som neskusal)

<img width="1023" alt="Žiadosť_o_aktiváciu_konta__ŽoAK_" src="https://user-images.githubusercontent.com/26273789/150489064-0c9c62e1-1ef7-4c0c-bcdd-10a192870747.png">

<img width="1354" alt="Rýchle_linky" src="https://user-images.githubusercontent.com/26273789/150489078-48e965fb-6048-476c-8cc8-6f2df7649a5f.png">
