### ISSUE TITLE
Preklep  v casti "Uvodny odsek"

### ISSUE THREAD

**Issue by vladovarga** [id-sk/id-sk-frontend#60]
https://idsk.gov.sk/komponenty/typografia#typography-lead-paragraph

<img width="1138" alt="Snímka obrazovky 2020-12-30 o 14 34 21" src="https://user-images.githubusercontent.com/2345695/103354624-5244c100-4aac-11eb-8c7f-d73770225d9d.png">

**Comment by PatrikKarambaPavlovsky** [comment]
Ahoj, vďaka a upozornenie - upravíme. Správne udaj je 24px.

**Comment by LubosKat** [comment]
issue fixed
