### ISSUE TITLE
Chybajuce popisy novych komponentov

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#66]
V ramci novych elementoch chybaju zmysluplne popisy, resp. usmernenia, v akych situaciach sa jednotlive komponenty maju pouzivat. Predbezne su publishnute tu:

https://id-sk-dev.herokuapp.com/komponenty/hlavicka-webove-sidla
Pri tomto by bolo fajn sa zamerat aj na povodnu hlavicku a vyspecifikovat, kedy sa ma ta pouzivat (resp. nema).

https://id-sk-dev.herokuapp.com/komponenty/footer-extended
Tu je nieco, bolo by fajn, keby toho bolo viac. Plus je v tom nejaky preklep - dvojbodka?

https://id-sk-dev.herokuapp.com/komponenty/karta
"Karty sa používaju na rôzne veci" 😄

https://id-sk-dev.herokuapp.com/komponenty/rozcestnik
"Rozcestník sa používa na navigáciu" ...

https://id-sk-dev.herokuapp.com/komponenty/stitok-varovanie-info 
"POPIS"

**Comment by LubosKat** [comment]
Dobry den,

[](https://id-sk-dev.herokuapp.com) je developerska verzia, nie finalna. 

Vsetky aktualne komponenty, vzory atd.. najdete tu: [](https://idsk.gov.sk/)
