### ISSUE TITLE
Duplikat Warning textu nazvany Štítok - varovanie / info

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#67]
Ku komponentu "oci vypalujuci" zlty banner https://id-sk-dev.herokuapp.com/komponenty/stitok-varovanie-info prebehla nejaka diskusia a testing?

Alebo to bol niekoho spasonosny napad, aby sa dala dat "VYRAZNA" informacia 😄 A potom vznikne este "VYRAZNEJSIA INFORMACIA" a dalsie a dalsie?

Zrejme duplikat uz existujucej komponenty https://id-sk-dev.herokuapp.com/components/warning-text

**Comment by frkosk** [comment]
@ljurena povenuješ sa tomuto issue prosím.

**Comment by ljurena** [comment]
Zdravim, 

oči vypalujúci lištu sme navrhli na základe focus ringu, ktorý sa aktuálne používa. Zatiaľ to nebolo testované s používateľmi, sme otvorení zmene farby :). Warning text je komponent skôr, ktorý sa využíva v texte.

**Comment by ondond** [comment]
Dobry den,
z mojej skusenosti s klientami (nie len egov) su prave "vyskakovacie okna" a upozornenia velmi nebezpecna vec. A vyuzivanie takychto bannerov (ak vobec su povolene) by malo byt podla mojho nazoru velmi opatrne a silno zvazovane (a zviazane prisnymi guidelines, ktore tam bohuzial chybaju).

**Comment by ljurena** [comment]
Zdravim, 

nikdy sme to nemienili použit ako pop up (tie su absolútne proti prístupnosti, ktorú musíme napĺňať). Je to myslené ako statický prvok pod hlavičkou ako to funguje na korona.gov.sk (v čase písania komentu to ale nie je použité). Je to myslené ako je tu : https://id-sk-dev.herokuapp.com/custom-components/header-extended/s-navig%C3%A1ciou-a-informa%C4%8Dnou-a-v%C3%BDstra%C5%BEnou-hl%C3%A1%C5%A1kou/preview  s tým, že sa to má používať dočasne, aby to nestratilo svoj efekt.

**Comment by ondond** [comment]
dakujem za otvorenu komunikaciu, zatvaram issue.

dufam, ze pribudne co najskor prisny guideline kedy vyuzivat takuto komponentu (a ze ju neuvidim v buducnosti na kazdom druhom statnom webe na uvodnej stranke 😄). chybajuci popis uz je adresovany v issue #66 .

**Comment by ondond** [comment]
dakujem za otvorenu komunikaciu, zatvaram issue.

dufam, ze pribudne co najskor prisny guideline kedy vyuzivat takuto komponentu (a ze ju neuvidim v buducnosti na kazdom druhom statnom webe na uvodnej stranke 😄). chybajuci popis uz je adresovany v issue #66 .
