### ISSUE TITLE
Untranslated messages

### ISSUE THREAD

**Issue by nekromoff** [id-sk/id-sk-frontend#9]
![image](https://user-images.githubusercontent.com/8550349/79787049-a8227000-8346-11ea-8939-ad87addaffec.png)
![image](https://user-images.githubusercontent.com/8550349/79787074-afe21480-8346-11ea-8795-5ff0699e1f10.png)

**Comment by LubosKat** [comment]
Dobry den,

dakujeme pekne za pripomienku. Opravene a nasadene.
