### ISSUE TITLE
Import fontawesome v _header-extended.scss 

### ISSUE THREAD

**Issue by otecfuras** [id-sk/id-sk-frontend#95]
Je tento import v _header-extended.scss v poriadku ?

`@import "./node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss";`

Podozrivý je trochu aj ten fo**r**t namiesto fo**n**t, v každom prípade nič z toho nie je spomenuté v dependencies package.json.

Pri pokuse použiť 2.2.0 verziu dostanem chybu:

ERROR in ./node_modules/@id-sk/frontend/idsk/all.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--13-3!./node_modules/@id-sk/frontend/idsk/all.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
5 │ @import "./node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@id-sk\frontend\idsk\components\header-extended\_header-extended.scss 5:9  @import
  node_modules\@id-sk\frontend\idsk\components\_all.scss 8:9                              @import

**Comment by LubosKat** [comment]
Dobry den,

v package.json-e je uvedena tato zavislost:
[](https://github.com/id-sk/id-sk-frontend/blob/master/package.json#L25)

`npm install` by mal vyriesit Vas problem. Pripadne `npm add @fortawesome/fontawesome-free`

Co sa tyka toho typa, tak je to skutocne fo**r**t a nie a nie fo**n**t
https://www.npmjs.com/package/@fortawesome/fontawesome-free

**Comment by otecfuras** [comment]
Dobrý deň.

fort vs. font beriem.

Ale v package.json-e, ktorý je súčasťou publikovaného npm balíka, zmienka o fort-awesome nie je žiadna a teda `npm install` nemá ako pomôcť. `npm add` + `npm install` v projekte používajúcom ID-SK je už len workaround ako to rozbehať, ale asi nie je OK, aby to vývojári takto sami diagnostikovali a riešili.
Je to jediný SCSS import tohto druhu v celom id-sk-frontend projekte (pre fontawesome icon font su assety priamo embedované v govuk/assets/fonts), som stále presvedčený, že toto súčasné riešenie nie je správne.

**Comment by LubosKat** [comment]
Dobry den,

plne s Vami suhlasim, ze to nie je riesenie ale len "quick fix". V nasledujucom release (buduci tyzden) bude tato pripomienka zapracovana. Dakujeme za Vase postrehy a pripomienky.

**Comment by MaNi4** [comment]
Dobrý deň,

aj po naimportovaní fontawesome mi hlási tú istú chybu. Kvôli zlej adrese k súboru.  U mňa funguje táto adresa k súboru. 
`@import "../../@fortawesome/fontawesome-free/scss/fontawesome.scss";`
Robím niečo zle? Ďakujem

**Comment by robertsopko** [comment]
Potvrdzujem, ze fontawesome styly su zahrnute v @id-sk/frontend baliku vo verzii 2.10.0 a nie je potrebne ich pridavat ako zavislost do projektu vyzivajuceho @id-sk/frontend
